/**
 * Megan Chu 1/14/17
 * please replace genome, k, L, and t in the main method with the inputs you want to test
 */

import java.lang.Math;
import java.util.ArrayList;
public class ClumpFind {
    public static void main(String args[]) 
    {
        String genome = "TGCGGCGTAGGGGCCGAGTAGTCCGTATTCGTCAAATTCGTGATTCTAGTCTGGTGTAGTCTGGTGTGATCCCTTATCTTACCCGCTACTCGTGGTAGAGTACGGGCAACGTACATAGTCTGGTGTACTGGCATTAGTCTGTAGTCTTAGTCTGGTGTGTCTGGTGTAGTCTGGTAGTCTGGTGTCTCGTTACTTCATTGCTTACAGTAGTCTGGTGTCCTATCTTAGTCTGGTGTTGGTGTTAAGCAGTTACCGTCCCTTTAGTCTGGTGTATAGTCTGGTGTAACTAACTAGTCTGGTGTGTTAGTCTGGTTAGTCTGGTGTGTTGTCCTAGTCTGGTGTATGCCGTAAAAATAGTCTAGTCTGGTGTTAGCAGGATGCGCGGTATGTAGTCTGGTGTCTCTCCCGGTCAACACAGATACAAAGCGGTCATTTAGTCTGGTGTTGTTGTAGTCTGGTGTGGTGTTATCGGAGATATACGTTGGGCTTTCTGCGCCGACGAGCAAAATGTCAGTAGGACGCGCAAATGAATGATATGTGCCAGCGAACTCGTCATTGCCCACGAGACCTAATAGTCTGGTGTGTGTACGATACCAGGTACTGTGGGTAGTCTGGTGTTGTGTGGGCTATATCTATATCCTATATCTCGTAATTGGGCTATTGGTGGGCTATATCGGGATTCTGGGCTATATCATACTTGGGCTATATCAACGGGGAAGAATGGGCTATATCTACTTCGTGTAGCTTCCGCCGCTCGTGTATATTGGGCTATATCTGGGCTATATGGGCTATATTGGGCTATATCATGGGGCAACATGGGCTATATCCGCCCCCTACTTCACCTGGGCTATATCCGTTTAAAGTGGGCTATATCATATCATGGGCTATATCACTTTTGTCCTGCGGCTAATGGGCTATATCCTCAGGGCTCCAGGAGTATCTCGAGCCCGAGGTCCTAATACTTCGACCTTGAAGTCTGTGGGCTATATCTATATCACCAGTCGTGCTGATTGGGCTATGGGCTATATCCAGTGTCGCTGGGCTATATCTGGGCTATATCGCGATACCATGCCGCAATCAACCCGCTGATGGGCTATATCCCTGGGCTATATCACTCTGGGCATGTAAGCATGGGCTATATCGGTGGGGCCCGTAAGGACTACTTCAAGTCTGCTATTTTGGGCTATATCGTGTGAGATGTTTTTACCCTGTCAGCTGGGGATCGGGCATTGGAGGTCGACCACCTCTTTTGAGCTTAACTGCGGGCGCAAACGCGGGCATTGGAGGCATTGGAGATCTTAAACTAACGAGACCGCGGGGAACCGGGCATTGGAGGCGATCGGGCATTGGATCTCTCTCGGGCCGGGCATTGGATCAAGCCTTCGGGCATCGGGCATTGGAGGCATTGGACAAAACCGACGATGGCTAAGTAGTCGAAATAGTCCGTCCAGGGTCGGGCATTGGAGGAGCACGGGCATTGGAATCGGGCATTGGAGCATTGGAGAAGCATCTCTGAACCAGGTGTGCGCGCTTATACGAGGAAACTTAGCCAGATCGGGCATTGGAAGATCGCAGTCTTCTAATTTGCTGACGCCCCCTTATGGTTATTGGACTACCTCCGGGCATTGGAACCCTTATGGTTCGGGCGGGCATCCCTTATGGTTAGCATCCCGGGCACGGGCATTGCGGGCATTGGATATTGGGCAGGTCCGGGCATTGGAAGCTTGCACTAGCTTACCCTTATGGTTGCCCTCCCTTACCCTTATGGTTCGCGAATTATGCCAGGAGGCTGCCTCGGGCCCTTACCCTTATGGTTGTCCTTGCGAGCTTAGGTGCACCCTTATGGTTTTACACATCGCCACCTTCCCTTATGGTTGACACCCTTCTCATTCCAGGCTGTTCCAGGTCAGGTAAATCGAATCCAGGCGCCCTTATGGCCCTTATGGTTAAAACAGGATCCCTCCCTTATGGTTTTTATGGTTACATCCCTTATCCCTTATGGTTAACCCTTATGGTTATCGGTGGCCGGAACCCCTTGGAACGCCCTTATGGTTTTATGGTTTGGCCCTTACCCCCCTTATGGTTCGTGTGCCCTTATGGTTGTCATCATCACCCCCTTATGGTCCCTTATGGTTGGATGTGCCCTTATGGTTAGATCCTCGCGTGAGTAGTGGCCGGAACTCTGGGTCAGCGTGGCCGGAACGTGGCCGGAACACCGTGGCCGGAACACATACAACGGTACTCACTCCGTGGCCGGAACATAGTCAGCACTGTGTCGGTGGCGTGGCCGGAACCTGCGACGTCAGACCATCTCCAAGATGTTTCTACTTGCTATTCTTATGTGGCGTGGCCGGAACGAGTGGCGTGGCCGGAACACGCCTCGCTCGATCATAGCTAACTCAACACGTGGCCGGAACGGCCGGAACTGATTTTGATGTAGGGTGGCCGGAACGCCGGAACTGTCGTGGCCGGAACACACCGACACGATATACCGACCGGATGCGGGCTTTGTTTTCCCAGGAACCGACTCCTGTGGCCGGAACACCAAGGTGGCCGGAACGTTCTCTACCTATGGTTTGGGCCATCTGCATGATAGCACTTAGCGTGTTGGAAGAATTTTGGGCAAAGGCTATCCTTAGGGTGTATGTTAGGGCGTGGATGCATGGCATAGTCCTACGCCTTCCTCTAAATATGCCGTCCCCTTGCGTGGGCGCTTGTCAAGCGGGCCGACGCAGCGGGGCCAGTGGGCGATATAGATCCGTTTCGTTTTTCCCATTGCGTGCATGGCGCGCGGTCAAAATGGTAAAACTGCCCGGGGTCCTCTATGAGACATTGCTCAGACACTGCCTGTTATTTCACGCCGAGATCGTTCGATTTCACTTACGCTTGGTAGCGAGTATTTAGGAGGAGTCTAAGGTTGACTTATACTCAAGGCCATATCTTCCCCAACCCAAAGTGCCGCGCCGCTAGTCTTGGCACTCTACTCAACGGCTACAAATTGGGGGGCCTCTCTGGCGTCCGGTTGCTAATTTCGCTACACACAGGTAGCTCGTTTACATGCGCGATTGCTACTGCGAATTGAGGGGGAAGGCGCCAGGCGAAAGTCCATCCTCACTCCCCTTGACCTAAGTTGGGGATTCGTCATTCGTCTATTCGTCTACCGTCTACCTACCAATGAGAAGCAAGAAAACTTTCCGAGTGAGTAATTCGTCTACCATTCGTCATTCGTCTACCTTGATTCGTCTACCCGTTTCTCGATAATCATACTAGTTTAGAGTAGGGATCCAATTCGTCTACCGTGTACATTCGTCTACCCTATGGTTTGAACTAGCCCCGGAGAACCTTGATTCGTCTACCCACCCCCGGAACTGCTGCGCTGATTCGTCATTCGTCTACCTTTCCCATTTTGTAACTGAAATTCGTCTACCATCTCGATATTCATTCGTCTACCCTGGTGTCTGGCCCTTCTCATATTCGTCTACCCTTGATGGTTATGGCATTCGTCTACCTTCGTCTACCGAACGCGACGCGACAGAGGTTATAAGGGTAGTCATGGATATTCGTCTACCAGAACGATTCGTCTACCCGAATGTGACATTCGTCTACCAAGGAATGCAGATTCATTCGTCTACCTCATTCGTCTACCACGCAGATTCGTCTACCGATATGGGAATTCGTCTAATTCGTCTACCGCTGACGCAGATCATGTGACGCAGATCTTGTAAGCTTGACGCAGATCATAAACTCGTGACGTGACGCATGACGCAGATCACTTTTTTGGCCCAGGAGTCTGACTGACGCAGATCCGCGACAACCCAACAATCTGACGCAGATCCTAGAACGCGAAATTTCAGGCGGACGACCCTAGCCTCTAGAACGCGAGTCCGGTATACGGTATATAAACGGCCAACTGACGCAGATCGACCCGAAGTGGGAGCCTCTAGAACGTGACTGACTGAGTCCGGTATAGATCAGATCATCAAGTCCGGTATAAGTCCGGTATATATACGTATTGCTAGATGACGCAGATCGATTCAACTAGTGATCGAATGATTTGAAGTCCAGTCCGGTATAAGAGAGTATGTGGTGCTCCACTTAGTCCGGTATATCCGGTATAACAAGTCCGGTATAAGTCCGGTATACGGGTCAGAGTCCGGTATAGTCCGGTATACCGGTATAGGTCAGTCAGTCCGGTATAAGTCCGGTATATATATCGTACGGGAAATTGATAGTCCGGTATATCCCACCGTCTGTGTCGGCCCCTCGCCAAGTCCGGTATATACCCAAAAAACCTCTTACCTCTAGTCCGGTATAGCATGTCCCAACTTAGTCAGTCCGGTATACCAAACACATGACCAAGAGTCCGGTATAGGTAGCAGGGGCAGCGCGATTAGTCCGGTATATAAAGGAAGAGTCCGGTATATCCGGTATAATTGACAGTGGATAAAGTCCGGTATAGATATATTATCGGACTTTCGTTTTATGGAGAATATGCTTAGCGCGGCGACTCCGGTAAGAATCTCTTATAGTGCTACTAGTCGGGCCTGCTGGACACTGTCTGTTCCAACGGAAACCCTTGTCTGAGCCATATACAAGTACTCGCCGTACGACTTTAGGCGGTATTACTAATATACATCCTCCCGTCGTAGCAATTGATCAATGCGCAAGTCTCGTGTACCGGATGTGCCCCTTACATTTTAGAACTGCGATTATAGGGCCTTGCTAAGTTCACTTTACACACACATAGTCCGCGGCGAACGTATTTATCAGGTTCTAGATTTCTCGCAAGTAAGTGGACCCTAATACAGGCTGGGATTAGACGGCCAGCGAGGAAACCAACCCCATGTATAGGAGGTTTATTAGTTCAACCCCAGAGCTCCGGTCTCAAGCTGACTCGGGATTTAGAACGTGTCCGGATCTGAACGCTTGTATCTGGTATTACGCGCTGGCGCTGGAATTACGCGATTACGCGCTGGGGGATTACGCGCTGATTACGCATTACGCGCTGATAGCTAGGTCGGCGGCATCGATTACGCGCTGCACCATATTACGCGCTGTTCACACGAGCCTCACTTATTACGCGATTACGCGCTGAAGACCCTGCGACTCCTTAACTGGTAACTCTTTTTGTGTGCCTTTGCGATTACGCGCTGACTTGATAATATTACGCGCTGACGCGCTGCTGTGCGCCAGGAAGTGTTAACCAACTCCTCTCGATTACGCGCTGTATTACGCGCTGATTACGCGCTGGTGGATGTGCCGGCGGATATTACGCGCTGCGCGATTACGCGCTGCCCATATTACGCGCTGGCTAGCGGTTGGAGCCATTACGCGCTGCATTACGCGCTGTACGGACGAGAACCCGCAACACGGCTCGTAGATTACGCGCTGATAAAAATTACGCGCTGCGCTGGAAGAGTGGGGTGTCCGGGCCGTGTTGTCACTTGATTATTACGCGCTGTGACATTTTGGAGAGTTTTAATTTGCTCACTCGGAACATGATGCAACGGGATTACGCGCTGAGCATACGTGCAATATTAGAGTACGACGTGCATGATACTAACTGTGCTCAGCGTGACTGAACAGCCATAGAAGACGAGTGGCGTGAAAATACTCACAGAGATCTTACACGACCGCTACCTAGCGAATAGTTTAGCATCGGGATCGCCAACAATGATGAAGGTGCCACCATTCTATGCTGTATGACGGACAGAACTACCGACAGAAGGCTGGGTACATTAGAGGGACCGAAAGCTCTGGAAAGCTCTGATAGGTTGAAAGCTCTGACAATAAAGGCCAGCCGAAAGCTCTGACTCGCTACATGGAAGTGAAAGCGAAAGCTCTGAGTATGACTTGTCGCCTGTGGTTACGCAAGTCAGTAAACCCGAAAGCTCTGATCTGAATTTGTCAGAAAGCTCTGATCACAAGTCGAAGCAAAGAGGAAGGGAAAGCTCTGATGCGACGAAATGTTAACGCGACGCCACTGTGCCAATCGGCCGATGACGAGAAAGCTCTGAGTTGGGAAAGCTCTGAAGAAAGCTCTGACGTTAGGTACGTCTGCCACGGGAAAGCTCTGAGAAAGCTCTGAGGGGTTGCTCAACGATACCAGAAGTTGAAAGCTCTGAGCTCTGATGAGCAGAAAGCTCTGGAAAGCTCTGAGAAATTGTTGAAAGCTCTGATGAACCCCGGTCCCATCGTTTATACCCCTTATACGAAAGGAAAGCGAAAGCTCTGAGCGAACGTGGGATAAAGGTGAAAGCTCTGAAAGGACTTTATACCCCGGGGCAAGCCCAGAAAGCTCTGACTCTGATAGAAAGCTCTGATTACGCCCCAAAGCACGCGAGATTATTTATACCCCGGCGGCCACTTGCACAGGTTCTTATTGGTCGATTTTTAGCCTGTTATACCCCGGAGAACGTATTATTTATACCCCGGCTGGTTGAATTTGGAAAAAATGGATTATACCCCGGGCACTGTGGCATACTAGCGATCTATGCTTATACCCCGGTTATACCCCGGATAATTGGCAGGGTGGGGAGATTATACCCCGGTTATACTTATACCCCGTTATACCCCGGATACTTATACCCCGGGATTTATACCCCGGCCTTATACCCCGGTTATACCCCGGCGGAACCGATTATACCCCGGGGGGAAAAACTAAGGTCGTTCCTGGCTCGCCTTATACCCCTTATACCCCGGGTGATAAGCTTATACCCCGGTATACCCCGGAAGGTGCATGCAATGTACGGTTTATACCCCGGTTCTACAATTTAATTACTTCTGCGGGAACATCCACCACGTAGAGTGGCCGTTAACTTCTCCCAGAACGTTTGCACCGGTAACCTGACCTCAGTACTGAATTTAAATCGGCGCCGTCTGACTCATTACGGGCGGAGAATTCCTAGTTCTCAGATTGCAAAGTCGTCCACACTACAGCTCATAGTGCCATTCTTGACCATGCGGACTGGGCAACTACCACTGGATGAGATTATTAGGAAAACCGCGGGTGATATCCCGAGGGTTGGGCTGCTTACTGTCGGGTAATGCTATTGTTCTCGCCGGTGGCAACGAGAGGCTCCCACAGGAGCCAATGACTTTCTTTGGAGCTCGCATATGAGGCTTACGGACGGGACATTAGGTACGACTACACATCCGTTTAGTTGCATATACTAGTTTGTCTATTTTCGGCGTAAATTGACGGTAGACCGAATTATTGACCACCTTGATACCGTGAAGCTGGCAACCGTTGTCAGACAGTCTTCAGCAGACCGATGGGACCGGGCCCCGTCATCCGGAGACCACGGGATAGAAATTGTCGTAACTAGGTGGGCGTCCTCCTCATGTTTTGATCGGTTAGCCCTCTGCCACGACCCTGGAACGAATGGCTAAGTACCAATTCGGGGATCGTTGATTACCGTTTACGTTCAATCTCGCTCGCGACCTGATGTACTTTATCTTCGTTAAGGGTCGCGAGGTTTTCTAAGGCTCTCAGGTGCTCTTGTTGCAAACATATGGATATGATACGCACTTAGGGCTAGTAGTTACTGAGTTTAGACCCTAACTTATCATGACGACGGAGTACTGCTGAAGGTGGTGTTAACTCCAAGCGATGAGTCTCCTGTTCACTTGTCTACTTAATTAGACACGCGATGGACTGGAATAGATGAGTGCTGGGTCTTCAGAACTATGAACTCCACATCCACTACTCGGTCGGGAAATTCGTTGAGACCCCAGTACAGTTAGTCAATTGACACTACATGTTGGTTAAGCTCATCGTACATGCTCCGGGTACGTCGAACCCCCTAGCCGCCACCTCGTCCTCCAGCTGCACTAACAGATCATCTGAAGACCAGGCGCAAAGAATCGGGAGTCATCATATTCAGGTGGCCTGACCCGAGCCGACAGACGCGTTCTGGACGATTGATCATACGTCCTAAGGACAACTAAGTAAAAGGTCAGTGTTAAACTCCCGCGCCATCCTGGACTCTCGCGTTATGCCATATGGAGGTCTTGGGAATCCGCGTAATGATTTTATATATCGGTTCTTTGGGTCTAGCGTATATTTTTCGCGTCTTAGGTGGAATCAACGTCGAGTCTTGTAGTCGAGCGGCGTGTTCCTAACGCAGTACCTACTATAAGTGCGATAAGCAGGCTTCTGGTTCGGACCCAGTATACAACAAGTTGTCACCCGGAACCGGAATTCGGTATACATAATATCCACCACGCGTTACTGTGATACCCAATGCGATGGTGTACCCTGAGAGTAAATAAAGTAAGGGCCGCTGGCCATGTCACGTGTATGATTTAACCGTTCGTGCTTGTCGTCTGCTTCCACAGCAATTGCTCCTTCTACGATTACCTGCATCCGATCTGTTATGCCCACCGCGCGAGGGTATCTTCGATCGACTATACTAGTTCGACTATACTTCTTTAAGTCGACTTCGACTATACTTATACTGTATATTTCGACTATACTGTCGACTATACTGCGTAACTCACTAGTCGACTATACTAGTCGACTATACTCGGAGTCAGGCAATCGACTATACTACTAGTGATGGTCTTAAAGGAGGTCGCATTTGAATCACTAAGTCGACTATACTACTATACTGCGTTAAGACCGGGATTCCGACCTAGTCCAAGATGGCTCGACTATACTTCCATTCGACTATACTGCGGAACGCTTGCCGAGACGTAATTTTCGACTATCGACTATACTCTGTCTACTCTTTCTGATTGCCACACCCTTTCGACTATATCGACTATACTCTGCCCTGCTTTATTAATTTATTCGACTATACTAGATGCGCCGTCTAGTAATTCGACTATACTAAATTATAACAGCCGATTTGGGCTACAATTAGCACTTTTAACTGCTGTATTATCGACTATACTGCCACTGGGTCCCTGCGCATTTGTTCGACTATATCGACTATACTTCGTCGACTATACTACCGCTTAAAACGTTTATTTTGTTTTTGTTTTCGACTATACTCTGAAGGAGGCGCGCCCGGTGCTGCGCGTGGTTTGTGCGTTTGTTTGTCTGAATAATACTTTGTTTGTCTCTGAATAATACCTGAATAATACCTTTGTTTTTGTTTGTCTATACCTGAATAATACCTGAATAATACCTGATTTGTTTGTCTATAATACCTGAATAATACCTGAATAATTTTGTTTGTCTACCTGAATAATACCTGAATAATACCTGAATATTTGTTTTGTTTGTCTTGTTTTGTTTGTCTTTTGTTTGTCTATAATACCTGAATAATACCTGAATTTTTGTTTGTCTTTGTTTGTCTAATACCTGAATAATACCTGAATAATACTTTGTTTGTCTTTTGTTTGTCTCTGAATAATACCTGAATAATACCTGAATAATACCTGAATTTGTTTGTAACAAATGGGTGTTTTTTTGTTTGTACAAATGGGTGTTGTTTGTACAAATGGGTGGGGTGGGTGGGTGACAAATGGGTGACAAACAAATGGGTGATGGGTGACAAATGGGTGACAAATGGGTGACAAATGGGTGACAAATGGGTGACAAATGGGTGACAACAAATGGGTGAATGGGTGACAAATGGGTGACAAATGGGTGACAAATGGGTACAAATGGGTGGACACAAATGGGTGAAATGGGTGACAAATGGGTGACAAATGGGTGACAAATGGGTGACAAATGGGTG";
        int k = 11;
        int L = 571;
        int t = 16;

        ArrayList clumps = clumpFinding(genome, k, L, t);
        for(int i = 0; i < clumps.size() - 1; i++)
        {
            System.out.print(clumps.get(i) + " ");
        }
        System.out.print(clumps.get(clumps.size() - 1));
    }

    public static ArrayList clumpFinding(String genome, int k, int L, int t)
    {
        ArrayList<String> clumps = new ArrayList<String>();
        int[] count = new int[(int)Math.pow(4, k)]; 
        // frequency array for all possible patterns

        String text = genome.substring(0, L);
        for(int i = 0; i <= text.length() - k; i++)
        {
            String pattern = text.substring(i, i+k);
            int pIndex = patternToNumber(pattern);
            count[pIndex]++;
            if(count[pIndex] >= t && !clumps.contains(pattern))
            {
                clumps.add(pattern);
            }
        } // we have counted all patterns in first L nucleotides

        // now we decrement first pattern, and increment next pattern
        // "sliding a window" without recounting
        for(int j = L - k + 1; j <= genome.length() - k; j++)
        {
            String front = genome.substring(j+k-1-L, j+k-1-L+k);
            int fIndex = patternToNumber(front);
            count[fIndex]--;
            String back = genome.substring(j, j+k);
            int bIndex = patternToNumber(back);
            count[bIndex]++;
            if(count[bIndex] >= t && !clumps.contains(back))
            {
                clumps.add(back);
            }
        }
        return clumps;
    }
        
    public static int patternToNumber(String pattern)
    {
        int num = 0;
        int shift = (int)(Math.pow(4, pattern.length())/4);
        for(int i = 0; i < pattern.length(); i++)
        // the rightmost nucleotide has the least # values
        {
            char c = pattern.charAt(i);
            if(c == 'A')
            {
                //do nothing
            }
            else if(c == 'C')
            {
                num += shift;
            }
            else if(c =='G')
            {
                num += 2*shift;
            }
            else
            {
                num += 3*shift;
            }
            shift = shift/4;
        }
        return num;
    }

    public static String numberToPattern(int index, int k)
    {
        String pattern = new String();
        double shift = Math.pow(4, k)/4;
        while(k != 0)
        // building pattern left to right
        {
            if(index >= 3*shift)
            {
                pattern = pattern + "T";
                index -= 3*shift;
            }
            else if(index >= 2*shift)
            {
                pattern = pattern + "G";
                index -= 2*shift;
            }
            else if(index >= shift)
            {
                pattern = pattern + "C";
                index -= shift;
            }
            else
            {
                pattern = pattern + "A";
            }
            k--;
            shift /= 4;
        }
        return pattern;
    }
}