public class MyClass {
    public static void main(String args[]) 
    {

        String text = "AACACGTTGAACTCACACGTTAGCAGAATTGTCGTAACACGTTCACACGTTGGCCTACACGTTGACACGTTGGAATATAACACGTTGACACGTTACACGTTCAACACACGTTACACGTTAAACTGAGAACACGTTTGTTCATTACACGTTAACACGTTCAACACGTTACTATCACACGTTAGTAACACGTTCACACGTTACACGTTACACGTTACACGTTCAACACGTTCAACACGTTTGAATGACACGTTACACAAAAAACACGTTGAGGAACACGTTCACACGTTTTCGTTGACACGTTTGTACACGTTCGTAGGACACGTTACACGTTGATCAGTTTGCAACACGTTACACGTTTGTCTGGCTGCACACGTTGTAACACGTTCTTACACGTTACACGTTACACGTTGACACGTTGACACGTTATGTGATACTAGTACAGACACGTTAGCACACGTTACACGTTTACACGTTGTCGTTTACACGTTACCATAGTACACGTTTCGGCGCACACGTTACACGTTGAACACGTTAACACGTTCTACACGTTGGTTACACGTTCTTACACGTTGCAGCTACACGTTGCAGGACACGTTACACGTTTACACGTTAACACGTTAACACGTTATACACGTTGAACGCTGTTAGGCGCACACGTTCACACGTTAACACGTTAACACGTTCCAGAAGACACGTTTACACGTTACACGTTCAGGTACTACACGTTCTCACACACGTTTACACGTTTATCGACCACACGTTGTAACACGTTAGTTTGGAACACGTTCGACACGTTACACGTTACACGTTACACGTTACACGTTCCCACACGTTCGTAGACACGTTAAGATACACGTTACACGTTGGACACGTTGGAGACACGTTGTACACGTTAAACACGTTCGAGGTATACACGTTCAGAACACGTT";
        String pattern = "ACACGTTAC";
        System.out.print(patternCount(text, pattern));
    }

    public static int patternCount(String text, String pattern)
    {
        int count = 0;
        for(int i = 0; i < (text.length() - pattern.length() + 1); i++)
        {
            if((text.substring(i, i+pattern.length())).compareTo(pattern) == 0)
            {
                count++;
            }
        }
        return count;
    }
}