public class MyClass {
    public static void main(String args[]) 
    {
        String dna1 = "TTGTTTTGGATGGCGGCGTACGATCGATAATGCGGCCAAGCACTGATCATCTTTCCCTCGTCCGTACTGTGTGGGGTCTCCCAGCGCGTCGGTCAGTGCACAGTTGTACAAAACCCCCAGCCTGATAGAGTTGACAACCGTCATCACATACGTTCGCATCATAAGCGCAGTATGCACCTCAGGTTTACGAGGTTGCAAGAGACCAGCCATTTAAAACTTCCACGCCGCAACTTTCGACTATAATGCTGCCCGCACTTTTCCCGGAATAGAGCAGAATTGCTGGTCGACCTTTCTGGGGATGAGCACCCTTGGTTGTGCCACATCAACACCAAGACGGGTATACGGTACGATGAGTGTCTTATGTGTCAGGTACGCGTTAACGATCTGATGTCGGGATCCCCAGTTTCACCAATAAGGGGAAAATGGCCCAACGGCAGCTGGCGTAGCAATGCACAACTGCTGAAGTGTATCCCATACGAGAAGGAATCCCTGCTCGTCATCTAGTAATCCCAACCAACGAGAAACTTCACTCCCCTTGCCTCCTCGCAGAATTGAGTTTAGTCAATGACATCTAAGCTCTCCCCTACTTACTTTAACGCGGAAGAAAGGCTAGGGTGATTCCCAAAACGCTGGCTATTGTAGGTCTGTTCGACATGCTTAGGTGCGGCTAACGGCCAAGCCCGCCGAAGATCACGGGCAAAGGGTAAAATAGCGAAGACTATAGAGCGTACCATCTAAAAAGGTCCGTATGATGGCTGATACAGGGGCAAACCTCGCCAAGCGTTAATATTGGCGAACATAGCGGAAGGCCATACACTATCGTATCCGCTTGTGTATGCATCGGTTTCGTAATGTCCTAGGCAGTGTTAACCACCGGGCGAAAGTATTAGAGTCAAGCGTCTGCTGTTGTCTTGTCGGGGCCGAACCCTATATATCCCCGAGCACTATATACGGATTCCCCCCTTATAGCTTCTGTACCAAAATTACTATCTAGTTGGACGGCTGAGTTTGCTTAGTTCACTCGTTAGGATTTGAAAAATGGAATAGTATGTGTTGAGCCCCGGCCGACCTAGGGCAGTTCATGCGAATCAGTTTGTGCCCGAATCGCCCTAGTCGATCGTATTGCATTTGTATCGATAACCCCAACCTAAGTATCTCGCATCTTCACGTAGCATCCTT";
        String dna2 = "ATAATGGCAGCATTCGCGGCGTGCTTATTCTTTTGTTGATGCTACCACGTATAAAGCCAAACGCAGTTGACAGTCGCCTGATGTGGCAAAGACGATGGGTAGGACGACAAAGAATCTAGTGTAGAAAGAGATATTAAACTTGCTCAGTTTGTGTGCAAGACTGACATATTCTCCTAATGGCAACTGATGCGAAGTTCATGATCTTATCACTCGCAATTGATCGACGTTCTCGATTCCTCACGCCCGTCAAATCACGGGACGTGCATAAACATCTATATTAGGGGCACTCCGTACAAATAACCAGGACGAACGCGCAACCAAGAATTCGTACGACCACAATTTCGAGTTTAGCGCCGTCCGCGGCCCCTTGCTGTGATTTAGATGTAAGTAGCGGGTTTATTGAATTTTGCCGGTCCTGGTATGACGAGCCCCATGTCGAGTACCCAGTGTGCGTAGCAAACTGGTTTTATCGACTAGACCTACTGAGGACACTGACTCGTAGCGAACTGTAAGCGTTTCAGGCTGGGGGAGCAGATGCAACCATCCCGCGTTTTTCGACACAGAATAGACGTGAACAGCGGCATGAGGGCTAAGTGTCTCATTCAAAGTGAAATCCCGAAACTAGCGTCGGTAGAGCCTCAGTATAGTGTGAATGCTTCGGAACGGCTAGGCGCTTGATCGCGCTAATCCACGGGCATAATAGACACCGTAACCACCTCCGTCCTACCACATATACACTTAAGGTAGACTCTCCTGGCCGGTACTACGGCTCAGCGGAAAGAGGAATATGGGCCTATTAGCGTGTAAAGGGGCCGCGCAACCTAGTTTCAGTCACAAGCTTTATTCCCGAATACATGCCTTTCGAACTTTGGAGTAACATGCCTTCGAAATTTCAGACACCGCCATCGCCTTCGCTTTAACCGGTTTCAACCCAATTCCACTTACATAGTTGGCTACCATCTGGCCACAGACCATAACATTACTTTTTTTACCGAGATGTTTAACTTTAGCGTCCTGGCGTGCCCGTCCCTGCGATGCCACCATCAGCAAGGGTATGGAGGTCGGTAGCTTGGGAGGGGATTCCGAGACCATATTCCACGCACTAAAGTAATACGCCCCAACCCTCGCCGATCCCACGGATCAGCGGTGGGCAGCGACTAAAGACCGTAGTGGTCGCAA";
        System.out.print(hammingDistance(dna1, dna2));
    }

    public static int hammingDistance(String dna1, String dna2)
    {
        char[] c1 = dna1.toCharArray();
        char[] c2 = dna2.toCharArray();
        int ham = 0;
        for(int i = 0; i < c1.length; i++)
        {
            if(c1[i] != c2[i])
            {
                ham++;
            }
        }
        return ham;
    }
}