/**
 * Megan Chu 1/14/17
 * please replace dna1 and dna2 in main method with the two strings 
 * you want to compare
 */

public class HamDist {
    public static void main(String args[]) 
    {
        String dna1 = "GGATATTCTGCAAACACGTAGACGAGGCGAATCGTATCGATCCTCGAACGACACGGAAGCCATCTTTAAAAATAGACTTCAGACTTAGAAACATTCAGTAAAGCGTTTTAGGGACAAGATGACACACAAAACCTCATGGAAGCTCGTTTACCTTATTCGGTTTCATTTACAGCTCCCACGGACAGCGTCGCCGGTCAATACCGTTCGGGGGTAGGATAGCTCAGGGTCTGGCGTATTTCTCACGTAGTGCTTACTAAGTAATTCGTTCAGAGTAGGGACGAGTCAAGTGCGACTGGCAACATGCCCCGCCCCCCCAGCGGATTTGTCCTAAGCTTAGAGTTAGTAAATGCAATATTCCATGCATCACAGGAAACGTCTGATTCGGCTAGCTAATTTGAGTGTGTTCAGAAGGTTGCCATATTCGATGGCAGTAGCGTTCTACCACTATCCTTACGCTGAAAGAAAGGGAAGGTGAAAAGCTATATCCCCATATGCCAAGCCTGGTAGGGCACTCGTTATTAGGAGATACTCACTCTGTAGGTTGTATGCTTCCAACAAAAGTACGAGGGCATTAGGTGATACCCTGCATGCACTACGGGGCTCTCGGAGTGGCCTTGGCCAAAACACCACCGCGTGACCCCGAGGAAAACTCTGTCGTATAAGGGTAATCGACCCCTATGATAATCCAAACAGATCAAGGCAAAACAACACACCGTAATGACGCTTCTCACTTCAATGCCACGTGGAGCCCTAGGGATCTTATCCCAGCCTTCGTGTGAGAAGTTTTAGTAGACTATTCGCGGGACCGTATTTCCGACTCGCTGGCATGTAGGGTTAATTCAAAGTTTATAAGAAATCTGTTCTGGTGGTCGCGAGTGCTTTGACAAGCCGCAATATTAAGCAGTAGAGAGCTACCGTCGCGGTATCCATATGACAGCCTTTCAGATCAGCAAAAACAGCCACCCATGTGGTCCATTGGGTACGGTGCTCAGGGATACGTTACGAAGTTTCGGCTGAAGCCGTGTCATCATAACGGAATCACGCTGTTCACGCAGAGTGACGCAGAGTTTGGGGCTCCTAGAAGCGTGGTCTTCCCAGGGGTGTCGCAGATCAATTTACATGGGTGA";
        String dna2 = "AAGTTCGCGGATAGCGGCATTGCGAGCACCTTCATGTCTTATTCTGCGGCATAATAAATCCAGTGTGCAATGACCCAATCGAAGCGATGTCTTTACACTGGTTTAACGGGACAGTCTCCCACGACGAGAATCAAGCTGCGCAATAGGGTGTACAGGGACTCGAAGGTACCCTTCGCCGTGGCTTTCGTGGGGTTTCTTCGAGGCTCAGGATTCATCACGCAAAGAGTGGACAGGCGACTAAAGCACTTGGGATAGGTGTTGACAGTACCTTTTGCACCGTAAGACGGGGACTTTGCGGGCCCTAACCTGCATTATATCCATAAGGCACACTGTCATGCCCATCGAGCTGTTAGAATATGCTTTAACGTCGACAATAAACCTCTCGTCCGGTTTTCTTTCTTCGAAGGAACCTCGGTCGGCACATCGTCGCAGTGATGCTTGGGAGATTAGTAAATATAGCAGAGCGTTACACCAGTCTTGTAGCTATGCATTTCGATGCAATATACCTCAAGTAGCTTAGTGAGACATGACACACCGCACCTTACGGCTGATCCCTGTCGATGTCCCACCCCGCCGAAAGCCCAGTAATGGTATAACAAACCGCCACAACGATTATCGCGTACAGCGCACAGTTAGCGCAGATTACATGTGATTTTATAGTATTCCTTACCCTGGTAAGCCTGTACAACCTCGGGTCATGCACTACGCTGCGGCTGATGATCAAGCCTTATGAGACGATATGTGGGGACGCCCCACAAGTCAGGTCGATTTTTGTGATCCTTAGCTCTCTACACGAAAAGAGAAACCCCCGGCGGATATAAAGAGAGTCGAGAATGTTGTACGGCTTTGGACGATACGATGCCGATGCGCACCTGTTTGAGCATCAAACGTCGGTAACGCGGAACTCAGCAGTGCCTGACCACCCCCGTATTTTTTACACGGGCACTGTGGTCTCAATAGTCAAGAATGACGCGAAGGACCGTGTCTCCCCCCGACGTTTTTTGCTAAGGTCATCCATGTCCAGCCCCTTCGTAGCACGACCATGTTATGCGTCCACACGTCGGCGTTTTTATTAGCTGGTCTTTCTAATTACGTTGATTTTAGGGCGCGGGCCGACCTGGTTTGGT";
        System.out.print(hammingDistance(dna1, dna2));
    }

    public static int hammingDistance(String dna1, String dna2)
    {
        char[] c1 = dna1.toCharArray(); // separate chars of dna
        char[] c2 = dna2.toCharArray();
        int ham = 0;
        for(int i = 0; i < c1.length; i++)
        {
            if(c1[i] != c2[i]) // compare chars
            {
                ham++;
            }
        }
        return ham;
    }
}