/**
 * Megan Chu 1/14/17
 * please replace text and pattern in the main method with the inputs you want to test
 */
public class PatCount {
    public static void main(String args[]) 
    {

        String text = "TGGGGCTGACTGGGCTGAGCGGTCGTCCCCCATTTCCGGGCTGATGGGCTGAGGGCTGAATAAGGGCTGAGGGCTGAAGGGCTGATCGTGTCTAGGGCTGAGGGGCTGAAGGGGCTGAACCTGGGCTGAGGGCTGAGGGCTGAGGGCTGAGGGCTGAAGATGGTGGGCTGAGTAGGGCTGAGGGCTGATCTTGTTCACTGGCTTAGGGCTGAGGGGCTGACTGGGCTGAGGGCTGATCGGGCTGAAGGGCTGATCGGGCTGACCGGGCTGAGGGCTGAAGAATAGGGCTGAGGGCTGAGGCCCTAGGGCTGAAGGGCTGAGGATTCTGGGGCTGAGGGCTGAGGGCTGAAGGGCTGAAGGGCTGACTGGGCTGAGCGGGCTGAGGGGCTGAAGGGCTGAGGGGCTGATCATGAGGGCTGAGGGCTGATCGGGCTGACCGGGCTGAGGGGCTGATCGGGCTGATAATCACTTTCGTGCGGGCTGAACGCATAGGGCTGAGGGGGGCTGAGGGCTGAGAGGGCTGAGGGCTGAAGACGGCGGGCTGAATAGCGGGCTGACCAAGGGCTGAGGGCTGAGGGCTGATGGGGGCTGAGCGGGCTGAGGGCTGAGGGCTGACCCCGGGCTGATAATAGGGGGCTGACCCCATCATAGGGCTGAAAGGGCTGAGGGCTGAGAGGGGCTGACCTGGGCTGACCGGGCTGAACACGGGCTGAGTTAGGGGCTGAGGGCTGAGGGGCTGATTCTGGGCTGACAAGGGCTGAATCGGGGCTGAGGGCTGACGGGCTGATGGTGGGCTGAGGGCTGAGGGCTGAGGGCTGAGGGGCTGACTTCAGTACTGGGCTGAGGGCTGATGGGGCTGAGGGCTGACGGGCTGAGGGCTGAGTAGGGGCTGACGTCGGGCTGAGGGCTGAGGGCTGATCGGGCTGAGGGGCTGACGGGCTGACTCTCGGGCTGAAGGGCTGAGGGCTGATAGGGCTGAGGGCTGACGAAGGGCTGACAAACCGGGGGCTGAGGGCTGAGGAGGGCTGATGAAGGGCTGATCATGGGCTGA";
        String pattern = "GGGCTGAGG";
        System.out.print(patternCount(text, pattern));
    }

    public static int patternCount(String text, String pattern)
    {
        int count = 0;
        for(int i = 0; i < (text.length() - pattern.length() + 1); i++) 
        // go through text
        {
            if((text.substring(i, i+pattern.length())).compareTo(pattern) == 0) 
            // compare substrings to pattern
            {
                count++;
            }
        }
        return count;
    }
}